// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dias.tracker.api.Data;

namespace dias.tracker.api.Migrations
{
    [DbContext(typeof(TrackerContext))]
    [Migration("20190725184045_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6");

            modelBuilder.Entity("dias.tracker.api.Data.Tables.BotResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("cooldown");

                    b.Property<DateTime>("created");

                    b.Property<string>("createdBy");

                    b.Property<bool>("isSuppressed");

                    b.Property<DateTime>("modified");

                    b.Property<string>("modifiedBy");

                    b.Property<string>("responses");

                    b.Property<string>("triggerText");

                    b.HasKey("id");

                    b.ToTable("BotResponses");
                });

            modelBuilder.Entity("dias.tracker.api.Data.Tables.Hamborg", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created");

                    b.Property<string>("createdBy");

                    b.Property<bool>("isSuppressed");

                    b.Property<DateTime>("modified");

                    b.Property<string>("modifiedBy");

                    b.Property<int>("pool");

                    b.Property<string>("text");

                    b.HasKey("id");

                    b.ToTable("HamborgText");
                });

            modelBuilder.Entity("dias.tracker.api.Data.Tables.Player", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("characterName");

                    b.Property<DateTime>("created");

                    b.Property<string>("createdBy");

                    b.Property<string>("discordHandle");

                    b.Property<bool>("isSuppressed");

                    b.Property<DateTime>("modified");

                    b.Property<string>("modifiedBy");

                    b.Property<string>("xivApiId");

                    b.HasKey("id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("dias.tracker.api.Data.Tables.PlayerData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created");

                    b.Property<string>("createdBy");

                    b.Property<bool>("isSuppressed");

                    b.Property<DateTime>("modified");

                    b.Property<string>("modifiedBy");

                    b.Property<int>("playerId");

                    b.HasKey("id");

                    b.HasIndex("playerId");

                    b.ToTable("PlayerData");
                });

            modelBuilder.Entity("dias.tracker.api.Data.Tables.Poll", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("active");

                    b.Property<string>("authorDiscordId");

                    b.Property<string>("channel");

                    b.Property<DateTime>("created");

                    b.Property<string>("createdBy");

                    b.Property<bool>("isSuppressed");

                    b.Property<DateTime>("modified");

                    b.Property<string>("modifiedBy");

                    b.Property<string>("name");

                    b.Property<string>("server");

                    b.HasKey("id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("dias.tracker.api.Data.Tables.XivJob", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created");

                    b.Property<string>("createdBy");

                    b.Property<bool>("isSuppressed");

                    b.Property<DateTime>("modified");

                    b.Property<string>("modifiedBy");

                    b.Property<string>("name");

                    b.Property<int>("role");

                    b.HasKey("id");

                    b.ToTable("XivJobs");
                });

            modelBuilder.Entity("dias.tracker.api.Data.Tables.PlayerData", b =>
                {
                    b.HasOne("dias.tracker.api.Data.Tables.Player", "player")
                        .WithMany()
                        .HasForeignKey("playerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
